# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"

epicsEnvSet NAME_AS_ENV_VAR my name is controllerOnePort

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Setting up Asyn Port controllerOnePort on 192.168.0.55:2002:
# AsynIPConfigure({{name}}, {{port}}, {{stop}}, {{parity}}, {{bits}}) 
AsynIPConfigure(controllerOnePort, 192.168.0.55:2002, 1, none, 8)
asynSetOption(9600, 0, N, Y)
asynOctetSetInputEos("\n")
asynOctetSetOutputEos("\n")
# motorSimCreateController(controller_asyn_port_name, axis_count)
# testing escaping:  {{enclosed in escaped curly braces}} 
motorSimCreateController(controllerOne, 4)

dbLoadRecords /epics/runtime/ioc.db
iocInit


# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 0, 20000, -20000, 500, 500)
# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 1, 20000, -20000, 500, 500)
# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 2, 20000, -20000, 1500, 1500)
# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 3, 20000, -20000, 2500, 2500)
# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 1, 20000, -20000, 100, 100)
# motorSimCreateAxis(controller_asyn_port_name, axis, axis_description)
motorSimConfigAxis(type='motorSim.simMotorController' entity_enabled=True controllerName='controllerOne' P='IBEK-MO-TST-01:' numAxes=4 port=type='asyn.AsynIP' entity_enabled=True port='192.168.0.55:2002' name='controllerOnePort' input_eos='"\\n"' output_eos='"\\n"' priority=100 noAuto_connect=False noProcessEos=False baud=9600 parity='none' crtscts='N' stop='1' disconnectOnReadTimeout='Y' bits='8' DESC='Simulated Motion Controller testing escaping:  {{enclosed in escaped curly braces}} ', 2, 20000, -20000, 100, 100)

