# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:diamondlightsource/python-copier-template
author_email: giles.knap@diamond.ac.uk
author_name: Giles Knap
description: IOC builder for EPICS and Kubernetes
distribution_name: ibek
docker: false
docs_type: sphinx
git_platform: github.com
github_org: epics-containers
package_name: ibek
pypi: true
repo_name: ibek
type_checker: mypy
