# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

{{controller.hostid}}AXIS_SETUP_{{num}}=$(SUPPORT)/motorTechnosoft/tml_lib/config/config.txt,AXIS_ID_{{num}}={{num}},AXIS_HOMING_SW_{{num}}=LSN
NAXIS=1
axis A2 C1 1AXIS_SETUP_{{ __utils__.counter("motorTML.axisCount", start=0) }}=$(SUPPORT)/motorTechnosoft/tml_lib/config/config.txt,AXIS_ID_{{ __utils__.counter("motorTML.axisCount", start=0) }}={{ __utils__.counter("motorTML.axisCount", start=0) }},AXIS_HOMING_SW_{{ __utils__.counter("motorTML.axisCount", start=0) }}=LSN

dbLoadRecords /ioc.db
iocInit

