# This file was automatically generated on Fri 07 Aug 2020 13:35:28 BST from
# source: /dls_sw/work/R3.14.12.7/support/BL45P-BUILDER/etc/makeIocs/BL45P-MO-IOC-01.xml
#
# *** Please do not edit this file: edit the source file instead. ***
#

# GK Containers Testing April 2021
# builder built IOCs can be converted to containers by dropping their DB and
# startup script in the config folder of the helm chart
#
# changes to boot script required
#    rename to ioc.boot
#    replace all hardcoded root folder with $(TOP)
#    replace references to dbLoadRecords to pass "$(THIS_DIR/dbname)"
#    replace dbLoadDatabase param with dbd/ioc.dbd
#    replace BL45P_MO_IOC_01_registerRecordDeviceDriver with ioc__registerRecordDeviceDriver

cd "$(TOP)"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '6000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/ioc.dbd"
ioc_registerRecordDeviceDriver(pdbbase)

# Create IP Port (PortName, IPAddr)

pmacAsynIPConfigure("BRICK1port", "172.23.59.21:1025")
pmacAsynIPConfigure("BRICK2port", "172.23.59.21:1026")
pmacAsynIPConfigure("BRICK3port", "172.23.59.21:1027")
pmacAsynIPConfigure("BRICK4port", "172.23.59.21:1028")
pmacAsynIPConfigure("BRICK5port", "172.23.59.21:1029")
pmacAsynIPConfigure("BRICK6port", "172.23.59.21:1030")


# Final ioc initialisation
# ------------------------
cd "$(TOP)"
iocInit
