# import json

# from apischema.json_schema.generation.schema import deserialization_schema
from ruamel.yaml import YAML

# from ibek.__main__ import ioc_schema

# from ibek.dataclass_from_yaml import yaml_to_dataclass
# from tests.pmac import PmacIOC

yaml = YAML()


def test_ioc_schema():
    """compare the schema generated by
    deserialization_schema(yaml_to_dataclass.get_module_dataclass()) with
    the schema generated by manually written dataclasses in tests/pmac.py"""


def test_deserialization():
    """ test that given an schema-adherant yaml file that this
    is deserialized without error to an object of the correct form"""
