# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

hello world from a
hello world from b
hello world from c

dbLoadRecords /epics/runtime/ioc.db
iocInit
