# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/repos/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase


# testValues TestValue
testValues test_value:Ref1.127.0.0.1

# testPreInit identifier TestValue
testPreInit A Consumer test_value:

dbLoadRecords /tmp/ioc.db
iocInit


testPostInit A Consumer test_value:

