# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

drvAsynIPPortConfigure(XBPM1.DRVip, 172.23.103.85:10001, 100, 0, 0)
asynOctetSetInputEos(XBPM1.DRVip, 0, "\r\n")
asynOctetSetOutputEos(XBPM1.DRVip, 0, "\r")

# drvTetrAMMConfigure(portName, IPportName, RingSize)
drvTetrAMMConfigure("XBPM1.DRV", "XBPM1.DRVip", 10000)
# ADCore path for manual NDTimeSeries.template to find base plugin template
epicsEnvSet "EPICS_DB_INCLUDE_PATH", "$(ADCORE)/db"

# NDStatsConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxThreads)
NDStatsConfigure("XBPM1.STATS.I1", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
# NDTimeSeriesConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxSignals, maxBuffers, maxMemory, priority, stackSize)
NDTimeSeriesConfigure("XBPM1.STATS.I1_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.I1' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='Cur1' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.I2", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.I2_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.I2' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='Cur2' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.I3", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.I3_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.I3' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='Cur3' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.I4", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.I4_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.I4' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='Cur4' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.SumX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.SumX_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.SumX' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='SumX' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.SumY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.SumY_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.SumY' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='SumY' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.SumAll", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.SumAll_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.SumAll' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='SumAll' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.DiffX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.DiffX_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.DiffX' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='DiffX' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.DiffY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.DiffY_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.DiffY' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='DiffY' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.PosX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.PosX_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.PosX' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='PosX' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
NDStatsConfigure("XBPM1.STATS.PosY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDTimeSeriesConfigure("XBPM1.STATS.PosY_TS", 2, 0, "type='ADCore.NDStats' entity_enabled=True PORT='XBPM1.STATS.PosY' NDARRAY_PORT=type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001' HIST_SIZE=256 P='BL03I-EA-XBPM-01' R='PosY' XSIZE=10000 YSIZE=0 ENABLED=1 NCHANS=1000 QUEUE=2 BLOCK=0 NDARRAY_ADDR=0 TIMEOUT=1 ADDR=0 MAX_THREADS=1 SCANRATE='I/O Intr' TS_PORT='$(PORT)_TS'", 1, 23, 0, 0, 0, 0)
# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxThreads)
NDStdArraysConfigure("XBPM1.ARRAYS.Arr1", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.Arr2", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.Arr3", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.Arr4", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.SumX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.SumY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.SumAll", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.DiffX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.DiffY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.PosX", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)
NDStdArraysConfigure("XBPM1.ARRAYS.PosY", 2, 0, "type='quadEM.TetrAMM' entity_enabled=True PORT='XBPM1.DRV' P='BL03I-EA-XBPM-01' R=':DRV:' QSIZE=20 RING_SIZE=10000 IP='172.23.103.85:10001'", 0, 0, 0, 0, 0, 1)

dbLoadRecords /epics/runtime/ioc.db
iocInit


# Increase precision of sample time for TetrAMM
dbpf("BL03I-EA-XBPM-01:DRV:SampleTime_RBV.PREC", "5")

