"""
A built in entity model instance for adding an IP address to consider before continuing.
(typically used to wait for motion controller and for autosave mounts on VxWorks)

"""

from typing import Literal

from pydantic import Field

from ibek.globals import GLOBALS
from ibek.ioc import BuiltInEntity

WAIT4IP_TYPE = "ibek.check_ip"


class Wait4IPEntity(BuiltInEntity):
    """
    A definition of Wait4IPEntity for the type checker.

    This is not really used - instead the dynamic class is created
    by the make_entity_model function is used.
    """

    type: Literal["ibek.check_ip"] = "ibek.check_ip"
    address: str = Field(
        description="The IP address to ping.",
    )
    delay: int = Field(
        description="The number of seconds to wait between successive ping requests.",
        default=1,
    )
    device: str = Field(
        description="The device name to use in the database record.",
        default="DEVICE",
    )
    repeats: int = Field(
        description="The number of successful ping responses to wait for before considering the communication established.",
        default=2,
    )
    timeout: int = Field(
        description="The number of seconds to wait for a response before considering the ping attempt a failure "
        "and exiting the IOC startup process; this will trigger a restart of the IOC pod by Kubernetes.\n"
        "A value of 0 means to wait indefinitely until communication is established.",
        default=10000,
    )

    def _process_entity(self):
        """
        If it doesn't exist already, create a shell script to wait for communication with given IP addresses.
        Add a command to this script to ping the IP address of the entity.
        """
        cmd = ""
        # Define the runtime directory to store the wait file, and create it if it doesn't exist
        runtime_dir = GLOBALS.RUNTIME_OUTPUT
        runtime_dir.mkdir(parents=True, exist_ok=True)

        # Remove the port number if it is included in the address, since ping commands expect just the IP address
        if ":" in self.address:
            self.address = self.address.split(":")[0]

        # Create the wait file path and initialize it with a header if it doesn't exist
        wait_file = runtime_dir / "wait_for_ip.cmd"
        if not wait_file.exists():
            cmd += "#!/bin/sh\n\n"
            cmd += "# This file is generated by Wait4IPEntity instances to wait for communication with specified IP addresses before continuing.\n"
            cmd += "# It is expected to be used in the startup script of the system to ensure necessary communication is established before proceeding.\n"
            cmd += "# The file is generated with append mode, so multiple Wait4IPEntity instances can add to the same file without overwriting each other.\n\n"
            cmd += "trap exit SIGTERM\n"
        wait_file.parent.mkdir(parents=True, exist_ok=True)

        # Create the ping command for the entity, which will be added to the wait file
        warning = f"WARNING: Communication with {self.device} at {self.address} could not be established."
        cmd += f"\n# Wait command for communication with {self.device}:\n"
        if self.timeout > 0:
            cmd += f"timeout {self.timeout} sh -c 'until ping -c{self.repeats} -i{self.delay} {self.address} >/dev/null 2>&1; do : echo {warning}; done'"
        else:
            cmd += f"sh -c 'until ping -c{self.repeats} -i{self.delay} {self.address} >/dev/null 2>&1; do : echo {warning}; done'"

        # Allow multiple Wait4IP entities to add to the same runtime file without adding duplicates.
        # The file is expected to be small, so additional reads should be efficient enough.
        # (class variable to track processed addresses could also be used, but discarded because of
        # ModelPrivateAttr management complexity and less robust to process multiple instances)
        with wait_file.open("a+") as stream:
            if self.address not in stream.read():
                stream.write(f"{cmd}\n")
