#!/bin/sh

# This file is generated by Wait4IPEntity instances to wait for communication with specified IP addresses before continuing.
# It is expected to be used in the startup script of the system to ensure necessary communication is established before proceeding.
# The file is generated with append mode, so multiple Wait4IPEntity instances can add to the same file without overwriting each other.

trap exit SIGTERM

# Wait command for communication with asynController1:
timeout 60 sh -c 'until ping -c2 -i1 192.168.0.55 >/dev/null 2>&1; do : echo WARNING: Communication with asynController1 at 192.168.0.55 could not be established.; done'

# Wait command for communication with controller0:
timeout 10000 sh -c 'until ping -c2 -i1 192.168.0.65 >/dev/null 2>&1; do : echo WARNING: Communication with controller0 at 192.168.0.65 could not be established.; done'

# Wait command for communication with controller1:
timeout 10000 sh -c 'until ping -c4 -i2 192.168.0.66 >/dev/null 2>&1; do : echo WARNING: Communication with controller1 at 192.168.0.66 could not be established.; done'

# Wait command for communication with controller2:
timeout 10000 sh -c 'until ping -c6 -i3 192.168.0.67 >/dev/null 2>&1; do : echo WARNING: Communication with controller2 at 192.168.0.67 could not be established.; done'

# Wait command for communication with controller3:
timeout 10000 sh -c 'until ping -c8 -i4 192.168.0.68 >/dev/null 2>&1; do : echo WARNING: Communication with controller3 at 192.168.0.68 could not be established.; done'

# Wait command for communication with asynController2:
sh -c 'until ping -c2 -i1 192.168.0.56 >/dev/null 2>&1; do : echo WARNING: Communication with asynController2 at 192.168.0.56 could not be established.; done'
