# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Create SSH Port (PortName, IPAddress, Username, Password, Priority, DisableAutoConnect, noProcessEos)
drvAsynPowerPMACPortConfigure("PPMAC1port", "none", "root", "deltatau", "0", "0", "0")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("PPMAC1", "PPMAC1port", 0, 8, 100, 1000)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("PPMAC1", 8)

dbLoadRecords /ioc.db
iocInit

