# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/repos/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase


# exampleTestFunction AsynPortIP Name Value
# A function that uses the AsynPortIP and Name
# to do something useful
exampleTestFunction  Yet Another Consumer of same port 
exampleTestFunction  Just One More Consumer of same port 

dbLoadRecords /tmp/ioc.db
iocInit

