name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,type-checking

  test:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python-version: ["3.13"]
      fail-fast: false
    uses: ./.github/workflows/_test.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      python-version: ${{ matrix.python-version }}

  docs:
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: write

  dist:
    uses: ./.github/workflows/_dist.yml

  pypi:
    needs: [dist, test]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_pypi.yml
    permissions:
      id-token: write

  release:
    needs: [dist, test, docs]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
